# PSI_INDEP
# function for creating weights independent on the data

# INPUT:
# - type - which one of the five LWS weight functions from the thesis should be used
# - n - the number of data rows
# - p - the number of regressors (including the intercept)
# - tau - the trimming constant in [1/2, 1); if tau = 0, it's calculated by the common formula tau = (floor((n+p+1)/2))/n
# - s - parameter for the type 2 weight function

# OUTPUT:
# - the vector of weights, that don't depend on the data


psi_indep = function(type = 1, n, p, tau = 3/4, s = 10){
  
  if(tau == 0 && !missing(p) && !missing(n)) {
    tau = floor((n+p+1)/2)/n
  }

  xgrid = seq(0+1/(2*n), 1-1/(2*n), length.out = n)
  
  if (type == 1){
    # Linear weights
    return(1-xgrid)
  }
  else if (type == 2){
    # Weights generated by the logistic function
    return( (1+exp(-s/2))/(1+exp(s*(xgrid-1/2))) )
  }
  else if (type == 3){
    # Trimmed linear weights
    return( (xgrid < tau)*(1 - xgrid/tau) )
  }
  else if (type == 4){
    # Weights generated by the so-called error function
    erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1
    return( 1 - erf(xgrid) )
  }
  
  else if (type == 5) {
    # Trimmed constant weights
    weights = rep(0, n)
    weights[1:n < tau*n] = 1
    return(weights)
  }
}

